CREATE TYPE "officer_role" AS ENUM (
  'QC',
  'LC',
  'CD'
);

CREATE TYPE "permission_action" AS ENUM (
  'view_resources',
  'reserve_own_quarter',
  'request_adjacent_transfer',
  'organize_transit',
  'requisition',
  'lower_retention'
);

CREATE TYPE "transfer_status" AS ENUM (
  'pending',
  'approved',
  'in_transit',
  'delivered',
  'rejected',
  'cancelled'
);

CREATE TYPE "leg_status" AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TYPE "route_type" AS ENUM (
  'land',
  'maritime'
);

CREATE TYPE "reservation_status" AS ENUM (
  'active',
  'released',
  'expired'
);

CREATE TABLE "quarters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(1) UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "disaster_level" int NOT NULL DEFAULT 2,
  "sea_access" boolean NOT NULL DEFAULT false,
  "is_hub" boolean NOT NULL DEFAULT false
);

CREATE TABLE "quarter_adjacency" (
  "quarter_id" int NOT NULL,
  "neighbor_id" int NOT NULL,
  PRIMARY KEY ("quarter_id", "neighbor_id")
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" officer_role NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_quarters" (
  "user_id" int NOT NULL,
  "quarter_id" int NOT NULL,
  PRIMARY KEY ("user_id", "quarter_id")
);

CREATE TABLE "permissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "disaster_level" int NOT NULL,
  "action" permission_action NOT NULL,
  "role" officer_role NOT NULL
);

CREATE TABLE "city_state" (
  "id" int PRIMARY KEY,
  "disaster_level" int NOT NULL DEFAULT 1,
  "retention_rate" decimal(4,3) NOT NULL DEFAULT 0.3,
  "updated_by" int,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "disaster_level_changes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "previous_level" int NOT NULL,
  "new_level" int NOT NULL,
  "changed_by" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "resource_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "inventories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quarter_id" int NOT NULL,
  "resource_type_id" int NOT NULL,
  "initial_quantity" int NOT NULL,
  "current_quantity" int NOT NULL
);

CREATE TABLE "reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quarter_id" int NOT NULL,
  "resource_type_id" int NOT NULL,
  "quantity" int NOT NULL,
  "requested_by" int NOT NULL,
  "starts_at" timestamp NOT NULL,
  "ends_at" timestamp NOT NULL,
  "status" reservation_status NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "transfers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_type_id" int NOT NULL,
  "source_quarter_id" int NOT NULL,
  "destination_quarter_id" int NOT NULL,
  "quantity" int NOT NULL,
  "route" route_type NOT NULL DEFAULT 'land',
  "status" transfer_status NOT NULL DEFAULT 'pending',
  "requested_by" int NOT NULL,
  "level_at_request" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "completed_at" timestamp
);

CREATE TABLE "transfer_legs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_id" int NOT NULL,
  "step_order" int NOT NULL,
  "from_quarter_id" int NOT NULL,
  "to_quarter_id" int NOT NULL,
  "status" leg_status NOT NULL DEFAULT 'pending',
  "approved_by" int,
  "decided_at" timestamp
);

CREATE TABLE "transfer_events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_id" int,
  "event_type" varchar NOT NULL,
  "rule_violated" varchar,
  "actor_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "calendar_events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_date" date NOT NULL,
  "title" varchar(150) NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "created_by" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "calendar_events" ("event_date");

ALTER TABLE "calendar_events" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE UNIQUE INDEX ON "permissions" ("disaster_level", "action", "role");

CREATE UNIQUE INDEX ON "inventories" ("quarter_id", "resource_type_id");

CREATE UNIQUE INDEX ON "transfer_legs" ("transfer_id", "step_order");

ALTER TABLE "quarter_adjacency" ADD FOREIGN KEY ("quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quarter_adjacency" ADD FOREIGN KEY ("neighbor_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_quarters" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_quarters" ADD FOREIGN KEY ("quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "city_state" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "disaster_level_changes" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventories" ADD FOREIGN KEY ("quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventories" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("requested_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfers" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfers" ADD FOREIGN KEY ("source_quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfers" ADD FOREIGN KEY ("destination_quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfers" ADD FOREIGN KEY ("requested_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_legs" ADD FOREIGN KEY ("transfer_id") REFERENCES "transfers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_legs" ADD FOREIGN KEY ("from_quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_legs" ADD FOREIGN KEY ("to_quarter_id") REFERENCES "quarters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_legs" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_events" ADD FOREIGN KEY ("transfer_id") REFERENCES "transfers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfer_events" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;